# Generated by Django 5.1.5 on 2025-02-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_rating_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='price',
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(choices=[('XXXXL', 'XXXXL'), ('XXXL', 'XXXL'), ('XXL', 'XXL'), ('XL', 'XL'), ('L', 'L'), ('M', 'M'), ('S', 'S')], default='XXL', max_length=1000),
        ),
    ]
