# Generated by Django 5.1.5 on 2025-03-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_coupon_code_coupon_code_coupon_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='vendor',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='store.coupon'),
        ),
    ]
