# Generated by Django 5.1.5 on 2025-03-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_cartorder_vendor_cartorder_coupons_and_more'),
        ('vendor', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='vendor',
            field=models.ManyToManyField(blank=True, to='vendor.vendor'),
        ),
    ]
