# Generated by Django 5.1.5 on 2025-02-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
