# Generated by Django 5.1.5 on 2025-03-17 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_cartorder_vendor'),
        ('vendor', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons_provided', to='vendor.vendor'),
        ),
    ]
