# Generated by Django 5.1.5 on 2025-02-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_cart_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tax',
            options={'ordering': ['country'], 'verbose_name_plural': 'Taxes'},
        ),
        migrations.AddField(
            model_name='tax',
            name='country',
            field=models.CharField(default='Nigeria', max_length=100),
            preserve_default=False,
        ),
    ]
