# Generated by Django 5.1.5 on 2025-03-07 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_cartorder_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorderitem',
            old_name='inittial_total',
            new_name='initial_total',
        ),
        migrations.RenameField(
            model_name='cartorderitem',
            old_name='shipping_fee',
            new_name='shipping_amount',
        ),
    ]
