# Generated by Django 5.1.5 on 2025-03-07 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_inittial_total_cartorderitem_initial_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='tax_fee',
            new_name='tax',
        ),
    ]
