# Generated by Django 5.1.5 on 2025-03-07 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_rename_initial_total_cartorder_initial_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorderitem',
            old_name='initial_total',
            new_name='initial_cost',
        ),
    ]
