# Generated by Django 5.1.5 on 2025-03-07 12:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_rename_initial_total_cartorderitem_initial_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitem',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
