# Generated by Django 5.1.5 on 2025-03-11 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_cartorder_oid_alter_cartorderitem_oid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartorder',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Cart Order'},
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='order_id',
        ),
    ]
